services:
  ## NGINX
  nginx:
    image: nginx:stable
    container_name: nginx
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  #PHP
  php:
    build: ./php
    image: pixwok-php
    container_name: php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  #DB PostgreSQL
  db:
    image: postgres:17.6
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: ${POSTGRES_TZ}
      PGTZ: ${POSTGRES_PGTZ}
    volumes:
      - ./db_data:/var/lib/postgresql/data